services:
  - type: web
    name: fitnex-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        value: ep-silent-voice-ap4yxo8z-pooler.c-7.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_S9TI3zFEQejA
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        value: fitnex_jwt_secret_key_change_in_production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: REDIS_HOST
        value: aware-parakeet-127501.upstash.io
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        value: gQAAAAAAAfINAAIgcDIwMzhmMTI5Nzk2ZGM0MGY4OTcwMTMwZjRmNjUwZTZmZA
      - key: REDIS_TLS
        value: true
      - key: WS_PORT
        value: 3001
